### ISSUE TITLE
AnonymousProfile should not be skipped when flattened into a single profile

### ISSUE THREAD

**Issue by mmoayyed** [pac4j/pac4j#1144]
In ProfileHelper:

```java
public static <U extends CommonProfile> Optional<U> flatIntoOneProfile(Collection<U> profiles) {
        return profiles.stream().filter((p) -> {
            return p != null && !(p instanceof AnonymousProfile);
        }).findFirst();
    }
```

Is there a reason as to why a function that is supposed to be a generic flattener method takes on the opinion that anonymous profiles do not matter and should not be included? 

This condition should not be part of this method. If there is anything in the codebase that can't or won't operate or support AnonymousProfile(s), then those *things* need to implement this condition, and leave the method here to be as generic as possible. It doesn't make sense for one to authenticate the request using an anonymous profile, and then not be able to retrieve it from the profile manager.

**Comment by leleuj** [comment]
The idea: either you want all profiles and you'll go through them to implement your logic or you just want one single profile and you want the more" meaningful" one.

That's why anonymous profiles should be skipped compared to authenticated profiles.

That said, if you have only anonymous profiles, you should at least get one and I admit there is certainly a bug here.

**Comment by leleuj** [comment]
@mmoayyed is this: https://github.com/pac4j/pac4j/pull/1147 ok for you?
