### ISSUE TITLE
how to use CAS proxy web with pac4j?

### ISSUE THREAD

**Issue by lapDog** [pac4j/pac4j#1300]
I read the official documents and the cas documents, but I didn't understand how to use pac4j for CAS proxy web App. Because there is no complete demo and documentation.
i use Springboot2.1.3+CAS5.3.7+pac4j4.1+shiro1.4, My configuration information is as follows:
``` java
   @Bean
    public CasConfiguration casConfiguration() {
        CasConfiguration casConfiguration = new CasConfiguration(casServerUrl+"login");
        casConfiguration.setProtocol(CasProtocol.CAS30_PROXY);
        casConfiguration.setPrefixUrl(casServerUrl);
        casConfiguration.setAcceptAnyProxy(true);
        CasProxyReceptor casProxyReceptor = new CasProxyReceptor();
        casProxyReceptor.setCallbackUrl(projectUrl+"/proxyReceptor");
        casProxyReceptor.setCallbackUrlResolver(new PathParameterCallbackUrlResolver());
        casProxyReceptor.setUrlResolver(new DefaultUrlResolver());
        casConfiguration.setProxyReceptor(casProxyReceptor);
        return casConfiguration;
    }
   @Bean
    public DirectCasProxyClient directCasProxyClient(CasConfiguration casConfiguration) {
        return new DirectCasProxyClient(casConfiguration, projectUrl);
    }
```
it's fine for SSO,But I want to use app1 to call app2's interface without having to log in again.My test classes are as follows:
``` java
    @RequestMapping("/proxy")
    @ResponseBody
    public ObjectDataResponse proxy(HttpServletRequest request, HttpServletResponse response) throws IOException {

        // 被代理应用的URL
        String serviceUrl = "http://localhost:9020/api/v1/index/findToDoCount";

        Object obj=request.getUserPrincipal();

        Pac4jPrincipal principal = (Pac4jPrincipal) SecurityUtils.getSubject().getPrincipal();
        final List<CommonProfile> commonProfileList = principal.getProfiles();
        final CommonProfile commonProfile = commonProfileList.get(0);
        CasProxyProfile casProxyProfile = (CasProxyProfile)commonProfile;
//        AttributePrincipalImpl attributePrincipal = new AttributePrincipalImpl("hjk");
//        casProxyProfile.setPrincipal();
        String proxyTicket = casProxyProfile.getProxyTicketFor(serviceUrl);
        System.out.println(proxyTicket);
        String result = restTemplate.getForObject(serviceUrl+"?ticket="+proxyTicket,String.class);
        return new ObjectDataResponse<>(result);
    }
```
I found the ticket was null,  because the CasProxyProfile.attributePrincipal  was null. but pac4jRealm is default setting, create SimpleAuthenticationInfo to shiro.  i don't know why... :(
If anyone knows what to do, please let me know. Thank you.

**Comment by daddyfatstaks** [comment]
Hola amigo muchas gracias

On May 7, 2019 7:57 PM, "HJK" <notifications@github.com> wrote:

I read the official documents and the cas documents, but I didn't
understand how to use pac4j for CAS proxy web App. Because there is no
complete demo and documentation.
i use Springboot2.1.3+CAS5.3.7+pac4j4.1+shiro1.4, My configuration
information is as follows:

   @Bean

    public CasConfiguration casConfiguration() {

        CasConfiguration casConfiguration = new
CasConfiguration(casServerUrl+"login");

        casConfiguration.setProtocol(CasProtocol.CAS30_PROXY);

        casConfiguration.setPrefixUrl(casServerUrl);

        casConfiguration.setAcceptAnyProxy(true);

        CasProxyReceptor casProxyReceptor = new CasProxyReceptor();

        casProxyReceptor.setCallbackUrl(projectUrl+"/proxyReceptor");

        casProxyReceptor.setCallbackUrlResolver(new
PathParameterCallbackUrlResolver());

        casProxyReceptor.setUrlResolver(new DefaultUrlResolver());

        casConfiguration.setProxyReceptor(casProxyReceptor);

        return casConfiguration;

    }

   @Bean

    public DirectCasProxyClient directCasProxyClient(CasConfiguration
casConfiguration) {

        return new DirectCasProxyClient(casConfiguration, projectUrl);

    }

it's fine for SSO,But I want to use app1 to call app2's interface without
having to log in again.My test classes are as follows:

    @RequestMapping("/proxy")

    @ResponseBody

    public ObjectDataResponse proxy(HttpServletRequest request,
HttpServletResponse response) throws IOException {



        // 被代理应用的URL

        String serviceUrl = "http://localhost:9020/api/v1/index/findToDoCount";



        Object obj=request.getUserPrincipal();



        Pac4jPrincipal principal = (Pac4jPrincipal)
SecurityUtils.getSubject().getPrincipal();

        final List<CommonProfile> commonProfileList = principal.getProfiles();

        final CommonProfile commonProfile = commonProfileList.get(0);

        CasProxyProfile casProxyProfile = (CasProxyProfile)commonProfile;
//        AttributePrincipalImpl attributePrincipal = new
AttributePrincipalImpl("hjk");
//        casProxyProfile.setPrincipal();

        String proxyTicket = casProxyProfile.getProxyTicketFor(serviceUrl);

        System.out.println(proxyTicket);

        String result =
restTemplate.getForObject(serviceUrl+"?ticket="+proxyTicket,String.class);

        return new ObjectDataResponse<>(result);

    }

I found the ticket was null, because the CasProxyProfile.attributePrincipal
was null. but pac4jRealm is default setting, create
SimpleAuthenticationInfo to shiro. i don't know why... :(
If anyone knows what to do, please let me know. Thank you.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/pac4j/pac4j/issues/1300>, or mute the thread

**Comment by leleuj** [comment]
Please use the mailing list fo questions: https://groups.google.com/forum/?fromgroups#!forum/pac4j-users
