### ISSUE TITLE
Single Logout with SAMLv2

### ISSUE THREAD

**Issue by pycloux** [pac4j/pac4j#139]
Hello,
Working with the SAML module I noticed that the single logout does not seems to work.
Actually despite a single logout URL exists in my idp-metadata.xml file, it is not used.

```
<SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="https://host/idp/profile/SAML2/Redirect/SLO" />
 <SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://host/idp/profile/SAML2/POST/SLO" />
 <SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:SOAP" Location="https://host/idp/profile/SAML2/SOAP/SLO" />
```

Looking at the SamClient code it becomes a bit obvious :-)
```
 // for now same for logout url
metadataGenerator.setSingleLogoutServiceUrl(getCallbackUrl());
```
This is actually the callback URL which is used by default which is rarely the same one as the logout URL.
Do you plan to read automatically the logout URL from the XML idp-metadata.xml ?
What would you advise as a workaround in the short term?

Regards,
PYC

**Comment by miremond** [comment]
Hi,

You are perfectly correct because... the SAML logout mechanism is not
implemented in pac4j. This is because originally pac4j targets the login
process; a generic logout mechanism reusable across all authentication
methods was not designed.
I would suggest you to look at the logout mechanism in pac4j-cas and try to
implement the same in SAML. Of course any pull requests are welcome.

Good luck

Best regards,

Michaël

2015-02-26 18:28 GMT+01:00 pycloux <notifications@github.com>:

**Comment by pycloux** [comment]
Hi Michaël,
Thanks for the answer.
I'll look at this.
