### ISSUE TITLE
PR #141 broke Google2Client

### ISSUE THREAD

**Issue by YogoGit** [pac4j/pac4j#150]
It appears that merge caused Google Client to fail automated tests as well as production failures with the same error, so I can not update to the latest version of the production jar.

https://github.com/pac4j/pac4j/issues/141

maven test -Dtest=org.pac4j.oauth.client.Google2ClientIT

...
12:53:34.694 [main] DEBUG org.pac4j.core.client.ClientIT - callbackUrl : https://accounts.google.com/ChangePassword?continue=https%3A%2F%2Faccounts.google.com%2Fo%2Foauth2%2Fauth%3Fresponse_type%3Dcode%26scope%3Dprofile%2Bemail%26redirect_uri%3Dhttp%3A%2F%2Fwww.pac4j.org%2F%26state%3DwtmFjIylmN%26client_id%3D682158564078-ndcjc83kp5v7vudikqu1fudtkcs2odeb.apps.googleusercontent.com%26hl%3Den-US%26from_login%3D1%26as%3D1d94c92567336a52&service=lso&sarp=1&scc=1&checkedDomains=youtube&pstMsg=0
12:53:34.694 [main] DEBUG o.p.oauth.client.BaseOAuth20Client - sessionState : wtmFjIylmN / stateParameter : null
12:53:34.694 [main] ERROR o.p.oauth.client.BaseOAuth20Client - Missing state parameter : session expired or possible threat of cross-site request forgery

I haven't debugged this much, but it doesn't appear this was tested at all.  Part of the reason is the automated test in pac4j-oauth have what appears to be an infinite recursion problem, so the tests never go anywhere and have to be aborted manually.

**Comment by leleuj** [comment]
You're right: there might be a regression. Integration tests simulate real authentication processes and maintaining them is really complicated. So they don't run by default.
There are also bench tests which take some time but don't output anything in my case because of this: https://github.com/pac4j/pac4j/blob/master/pac4j-core/src/test/resources/logback.xml#L23.

Maintaining pac4j and all *-pac4j libraries takes me a lot of time: any help will be appreciated.

**Comment by leleuj** [comment]
Someone reported the same problem: https://groups.google.com/forum/?fromgroups#!topic/pac4j-users/40FhzXrK3Z8

**Comment by leleuj** [comment]
I made a test using this demo: https://github.com/kristiankime/play-pac4j-heroku and it works.

Would you mind joining the thread on the mailing list or opening a new one with your logs (*DEBUG* on `org.pac4j`)?
