### ISSUE TITLE
PKCE support in OIDC client attempts to store non-serializable attribute in JEE session

### ISSUE THREAD

**Issue by phillipross** [pac4j/pac4j#1635]
Changes for PKCE from pull request #1630 introduce a problem where an attempt is made to store a non-serializable attribute in the session.

Specifically, the CodeVerifier class is not serializable. This breaks in the servlet containers which strictly enforce serializable session attributes.  A concrete example can be seen with https://github.com/pac4j/jee-pac4j-cdi-demo which uses payara-micro maven plugin to deploy and run the war (as opposed to jetty which is used in https://github.com/pac4j/jee-pac4j-demo

I've confirmed that the Google OIDC demo link in jee-pac4j-cdi-demo is broken with pac4j v4.0.3 but works when reverted to v4.0.2.  Also, I've confirmed that when using v4.0.3 and using `setDisablePkce(true)` in the config, it DOES work.

**Comment by papegaaij** [comment]
That's an unfortunate oversight. We should store the value of the secret in the session and reconstruct it for the token request. @leleuj I can create a PR this Monday if needed. I'll also submit a bug report at the OIDC library, because CodeVerifier is meant to be stored in the session. It should have been Serializable, like State is.

**Comment by papegaaij** [comment]
https://bitbucket.org/connect2id/oauth-2.0-sdk-with-openid-connect-extensions/issues/303/codeverifier-should-be-serializable

**Comment by leleuj** [comment]
I just updated to com.nimbusds:oauth2-oidc-sdk to v8.11. Isn't it enough to fix the issue?

**Comment by papegaaij** [comment]
Yes, it should be. The bug was fixed upstream. I'm not even sure if this warrants new release from pac4j. Users that run into this issue can easily update com.nimbusds:oauth2-oidc-sdk to 8.11 themselves using dependecyManagement.

**Comment by leleuj** [comment]
Yes, I think so.

**Comment by phillipross** [comment]
I'd agree that a new release isn't absolutely necessary since there are workarounds, but I'd recommend leaving this issue open until the next release (whenever that may be).  If anybody else runs into the issue, they'll find a solution/workaround quicker if the issue is open.

**Comment by johnjcool** [comment]
Hello, we are using the code challenge. pkce is working in our environment. but we have to configure a client secret and the client secret is also be send within the token request. the specification addresses the pkce to get rid of the static client secret to use instead the generated code_verifier. is this on the roadmap? is this a new issue?

**Comment by papegaaij** [comment]
Hi @johnjcool,

PKCE serves a very different goal than the secret does. The code verifier ensures that the code cannot be used by a malicious client. The secret is for authenticating the client. When your client cannot store a secret because it is public, such as a browser based app, you should use a client registration without a secret. PKCE will help securing the OAuth flow in a public client, but it will not replace the secret. Without a secret, the client is only identified, not authenticated and as such can easily be spoofed.

I don't know if pac4j already supports OAuth/OIDC without a secret, but imho it only makes sense in a Java desktop app in the case of pac4j. A server-side application can and should always use a secret.

**Comment by johnjcool** [comment]
hi @papegaaij,
thanks for your explanation. I get it.

**Comment by leleuj** [comment]
Fixed in v4.1.0
