### ISSUE TITLE
OIDC direct client via Bearer token

### ISSUE THREAD

**Issue by jmntn2000** [pac4j/pac4j#1679]
Utilizing HeaderClient and UserInfoOidcAuthentiactor to support Bearer token PAC4J creates the OidcProfile that is instantly expired.  

The default logic sets the expiration based on current time plus access token's lifetime or defaults to zero.  This results in the profile manager throwing out the profile due to OidcProfile.isExpired() returning true.    It seems to me a more reasonable approach would be to set the OidcProfile expiration date to be equal to the access token expiration?  It is unusable the way it currently is.

see:
https://github.com/pac4j/pac4j/blob/c89589b10080cdc161e18a56e240188747b957c5/pac4j-oidc/src/main/java/org/pac4j/oidc/profile/OidcProfile.java#L103

seems like better solution would be set to access_token.exp attribute.

**Comment by leleuj** [comment]
I'm not sure to understand what you want to do. Can you give me some code example?

**Comment by sylantro** [comment]
I'm also stumbling across this "immediate expiry" problem too. It seems to have been caused by https://github.com/pac4j/pac4j/pull/1630 (PKCE support).

My guess as to the cause...

The changes made to `OidcProfile.isExpired()` expect the `AccessToken.lifetime` to be set properly, but it's always initialized to 0 resulting in immediate expiry:
https://github.com/pac4j/pac4j/commit/49921f03c48df251571413bed9c8b35fb6fcce2e#diff-b93c64bc49ca904cdca39403e8275defR107

Looks like the `BearerAccessToken` classes from Nimbus OIDC SDK don't initialize the `lifetime` field from the JSON `exp` attribute when using the `BearerAccessToken( String )` constructor. The `lifetime` is only ever initialized when `BearerAccessToken.parse( JSONObject )` using the `expires_in` attribute.

I think we can fix this by changing `OidcProfile.getExpiration()` to retrieve the `OidcProfileDefinition.EXPIRATION_TIME` attribute (which maps to the `exp` JWTClaim attribute) instead of `OidcProfileDefinition.EXPIRATION`:

```
    public Date getExpiration() {
        return (Date) getAttribute(OidcProfileDefinition.EXPIRATION_TIME);
    }
```

**Comment by jmntn2000** [comment]
I'm thinking it would be better to set it based on the access token expiration.  So change OidcProfile.setAccessToken method to use the exp attribute of bearer token instead of trying to calculate a new expire based on current time and lifetime which typically doesn't exist.  If you want I can make the change and create a pull request.

**Comment by sylantro** [comment]
> So change OidcProfile.setAccessToken method to use the exp attribute of bearer token instead of trying to calculate a new expire based on current time and lifetime which typically doesn't exist.

That's a better approach! Thank you.

**Comment by leleuj** [comment]
@jmntn2000 Yes, please submit a PR. It will be easier to see the proposed changes.

**Comment by sandeshindi** [comment]
When can we expect this fix ?

**Comment by leleuj** [comment]
I was waiting for a PR, but it don't see anything come. I'll take a closer look at the end of this week.

**Comment by jmntn2000** [comment]
I can get this done end of this week.  I have the change done just need to test it.

**Comment by jmntn2000** [comment]
pull request created
