### ISSUE TITLE
Rewrite README

### ISSUE THREAD

**Issue by leleuj** [pac4j/pac4j#177]
Let's make it shorter and more straightforward

Move from the technical components into the clients?
Move from the source code into the core concepts?

**Comment by mmoayyed** [comment]
Does it make sense to move much of the doc into the project wiki space?

**Comment by leleuj** [comment]
You read my mind ;-)

I just moved the identity providers list into the https://github.com/pac4j/pac4j/wiki/Clients page.

I'd like to keep in the README:
- a general presentation of pac4j (engine)
- a list of all frameworks implementing it (with links)
- a list of the supported authentication mechanisms (with links)
- the general algorithm to use it
- mandatory technical information (versions, how to build, repository)
- mailing lists

**Comment by mmoayyed** [comment]
That sounds perfect to me. In general, I think all material, compelling enough, that would entice and convince a given developer to use pac4j belong in a readme. Like an ad!

**Comment by leleuj** [comment]
@miremond @mmoayyed : what do you think of the my https://github.com/pac4j/pac4j/blob/master/README.md? I am quite satisfied...

**Comment by mmoayyed** [comment]
I think it's great. Few more suggestions:

1. Move the logo to the very top of that page
2. Use github badges to show the latest available release (see the CAS readme for example)
3. Add tags to highlight code snippets with syntax. 
4. Instructions on how to build from source, how to checkout, how to skip tests, how to run IT tests, etc. 

Otherwise, excellent.

**Comment by mmoayyed** [comment]
Also to keep future maintenance at a minimum rate, how about we reduce the size of "Supported authentication mechanisms:" block and only list supported protocols without any references to specific modules. The link that describes everything should be the main point of reference.

**Comment by leleuj** [comment]
OK. Thanks for the feedback...

**Comment by miremond** [comment]
Hello

I am a little bit late here. I have not many things to add to what Misagh
said but I wonder about the "implementation" part:
The java code given as example is relevant for people wanting to implement
pac4j in a new web framework and this is a good thing to have. But I am not
sure the README is the correct place, I think the majority of developers
will just reuse one of our existing binding.

But maybe this was intentional, what do you think?

2015-06-17 11:36 GMT+02:00 LELEU Jérôme <notifications@github.com>:

**Comment by leleuj** [comment]
The "implementation" part targets the developers who want to implement `pac4j` in their framework. Indeed, there is no documentation for people who want to use pac4j and that's pretty logical because they should read the documentation of `myframework-pac4j` library.

I think I should add some information to explain that clearly.

**Comment by leleuj** [comment]
Just updated the README this way: what do you think?

**Comment by miremond** [comment]
+1

2015-06-18 10:30 GMT+02:00 LELEU Jérôme <notifications@github.com>:

**Comment by leleuj** [comment]
It's always a work in progress, but I assume we're good.
