### ISSUE TITLE
OidcProfile is not Serializable

### ISSUE THREAD

**Issue by alkemist** [pac4j/pac4j#194]
This field is not serializable: https://github.com/pac4j/pac4j/blob/master/pac4j-oidc/src/main/java/org/pac4j/oidc/profile/OidcProfile.java#L35

**Comment by mmoayyed** [comment]
And it should be serializable because...? Are you seeing a particular error?

**Comment by alkemist** [comment]
Because it implements java.io.Serializable by extending UserProfile.

This prevents it from being used in a distributed session.

**Comment by leleuj** [comment]
Indeed, all user profiles must be serializable because user profiles always go into a web session or a cache and that requires Java serialization.
In CAS, as the attributes of the user profiles are used to built the principal (part of the main `Authentication` object), it must be serializable via Kryo when saved into Memcached.

**Comment by mmoayyed** [comment]
Problem here is that the class BearerAccessToken is not part of pac4j. I'll post a solution shortly.

**Comment by leleuj** [comment]
Thx
