### ISSUE TITLE
Add a context Object in the init() method

### ISSUE THREAD

**Issue by leleuj** [pac4j/pac4j#199]
For the https://github.com/pac4j/pac4j/blob/master/pac4j-core/src/main/java/org/pac4j/core/util/InitializableObject.java, to be able to pass the web context in some case, linked to https://github.com/pac4j/pac4j/issues/198

**Comment by leleuj** [comment]
See: https://github.com/pac4j/pac4j/issues/193

**Comment by morungos** [comment]
Yes, this is definitely the right direction, although I don't know how to do it. I've started on a workaround but the context is not available in `ClientRealm#internalGetAuthenticationInfo`, calling `getUserProfile` with a null context. I'm fairly sure this also means that nonces are borked, as the context is needed to validate them in `ClientRealm#internalGetAuthenticationInfo`.

**Comment by morungos** [comment]
Oh but now I'm questioning whether this is the right approach. Clients are persistent across requests, so they should expect different contexts all the time. The OIDC issue is a strange one in that the context is needed because we want a value which will be constant. But the nonce issue is a different one, and there the context should be different between requests. 

Perhaps a better model is to include the context in the OidcCredentials? Then the context ought to be accessible everywhere it's needed, and it'll be consistent with the callbacks. Am I making any sense or am I talking garbage?

**Comment by leleuj** [comment]
You raise a good point: the `init()` method will be called once where as the *web context* will be different every time. It doesn't make sense. I will close this one.

I guess the solution is really to open more the `OidClient` and override the methods that needs to be redefined.

**Comment by morungos** [comment]
I've actually got a working implementation (as far as I can tell) by storing the context as a transient in the credentials. 

My modified classes are at: 

 * https://github.com/pughlab/tracker/blob/develop/src/main/java/ca/uhnresearch/pughlab/tracker/security/AbsolutifyingOidcClient.java
 * https://github.com/pughlab/tracker/blob/develop/src/main/java/ca/uhnresearch/pughlab/tracker/security/ContextualOidcCredentials.java

So I've had to revise the class entirely rather than extend it, but I think the solution of embedding non-a persistable context in the credentials has worked so far. This is mainly needed to ensure we get the context in the `retrieveUserProfile` which, although it's passed a context, as far as I can read from the code this context is never valid in practice. It's only passed by test cases, and will be null for real use. This is a bigger change, as getting the context passed here is really the problem. 

I think my solution is a big kludge, but it's helped pin down the problem, and it at least gets me as far as the key verification. 

Now for the next problem: the ConnectID SDK version can't work with Google OIDC because version 3.4.1 doesn't adhere to the core spec on multiple keys. I'm talking to them [here](https://bitbucket.org/connect2id/oauth-2.0-sdk-with-openid-connect-extensions/issues/138/google-openid-connect-cant-locate-which) on that but there will be a pac4j change to follow on that.

**Comment by leleuj** [comment]
Thanks for keeping me posted.

Passing the context in the credentials is a bit strange at first sight, but it works and indeed, credentials are retrieved from a context, the method signature is obvisous: `public C getCredentials(WebContext context)`.

Feel free to open a new PR for the ConnectID SDK update.

**Comment by baxterj** [comment]
Hi @leleuj - is there any chance of this credentials/context pattern making its way to master for the OidcClient? I am also running up against the NPE in retrieveUserProfile when using nonce, as 'null' is passed in by the ClientAuthenticationProvider#authenticate(final Authentication authentication)

**Comment by leleuj** [comment]
I tested the OpenID support with https://github.com/pac4j/j2e-pac4j & https://github.com/pac4j/play-pac4j and it works.

Is the issue specific to https://github.com/pac4j/spring-security-pac4j? Or can I reproduce it using another library?

Feel free to open a PR on pac4j or spring-security-pac4j.

pac4j v1.8 will be released in one month or two so it's the perfect time to fix issues.

**Comment by morungos** [comment]
@leleuj I've had a mix of OpenID Connect issues with pac4j, all of which I *seem* to have resolved, but my IT people are being real slow, so I can't really test out the providers the way I'd like. 

The main issue I've had is working with Google is very broken, because there's no logic to handle key rotation. This means a Google OIDC service works sometimes, but not reliably, and never for more than about half a day, before the keys change. Most of these problems are actually not in pac4j, but in the nimbus layers, which were/are not fully supporting OIDC with multiple keys. However, they can't be completely handled there, as the Client needs to handle a new MissingKeyException (that was my approach, anyways) and react by going back to the JWKS endpoint to get more keys and try again if needed. 

None of these issues were ever apparent with, e.g., the Mitre provider, because it didn't do key rotation for me. Most of what I've done is now at: https://github.com/pughlab/tracker/tree/develop/src/main/java/ca/uhnresearch/pughlab/tracker/security in the develop branch, and in particular the `AbsolutifyingOidcClient` and the `RotatingJWTDecoder`. If you'd like me to spend a little effort backporting these for you into distinct PRs, I'm happy to do so. It feels like they are logically separate issues.

**Comment by mmoayyed** [comment]
To me, this sounds like a legitimate use case. I would vote for a PR to see what a solution might look like and how feasible it might be to include in pac4j.

**Comment by leleuj** [comment]
The issue with Google will be fixed in the next version of the Nimbus lib. See: https://github.com/pac4j/pac4j/issues/218

-> http://connect2id.com/blog/nimbus-jose-jwt-4.0-rc1

**Comment by morungos** [comment]
Yes, they told me that. I did actually try with some of that too at its snapshot stage, but there seemed to be API differences. However, if you want to move to nimbus 4, I'll work on that basis. It's your call. It's probably the best move as they said it could handle some of the key rotation logic.

**Comment by leleuj** [comment]
With the new pac4j version 1.8, I think it's the perfect time to upgrade the Nimbus version library.

**Comment by leleuj** [comment]
@morungos: the `nimbus-jose-jwt` 4.0 has been released, but we need to upgrade the `oauth2-oidc-sdk`: any progress on this?

**Comment by morungos** [comment]
Slow progress, sorry. I was blocked from deploying OIDC for a couple of weeks due to IT concerns internally, now resolved. I'm also trying to get the components tested enough, too. I do have to deliver this internally next week, so there'll have to be progress by then.

**Comment by leleuj** [comment]
Thanks for the feedback.

**Comment by leleuj** [comment]
@morungos : I finally took a look at the OpenID Connect support. The upgrade was so easy: https://github.com/pac4j/pac4j/pull/266

Any feedback will be appreciated.
