### ISSUE TITLE
Make Credentials and UserProfile? cleanable

### ISSUE THREAD

**Issue by leleuj** [pac4j/pac4j#250]
For Spring Security at first.

See: https://github.com/pac4j/spring-security-pac4j/pull/13

**Comment by JacobASeverson** [comment]
Just opened PR https://github.com/pac4j/pac4j/pull/254 . A few things to note:
* I wasn't sure where you would want `Clearable` in the package structure since it is used by both `UserProfile` and `Credentials`. Let me know if you think it should go somewhere else.
* Looking through the `UserProfile` implementations, I wasn't sure what should be cleared for most of them. The only Implementation I added was for the `OAuth20Profile` type.

**Comment by JacobASeverson** [comment]
Just pushed a commit to the PR with those last changes we were discussing, let me know if there is anything else you can think of. Thanks!

**Comment by leleuj** [comment]
Just merged. Thanks again.
