### ISSUE TITLE
Allow TwitterClient to accept a ProfileCreator

### ISSUE THREAD

**Issue by kyleboon** [pac4j/pac4j#265]
It seems like all clients should be able to specify a ProfileCreator. 

I have a site where users can login either with a username and password or with twitter. I'd like to add an account id to a common profile. It's very cumbersome to be able to do this with the TwitterClient, and even more cumbersome to have it work seamlessly with the HttpProfile.

**Comment by leleuj** [comment]
Yes, it seems so. You could override the `getUserProfile()` method in the `TwitterClient` to use a new `TwitterProfileCreator`. I guess the `ProfileCreator` could gain new methods, like `preCreation()` and `postCreation()`, this last one to handle authorizations generations.

At least, you already have two things to help you handle extra parameters in the profiles. The first one is that since pac4j v1.8, you can put any attribute even if it's not in the profile's definition. The second one is the `AuthorizationGenerator` concept which can be used to populate your user profile with roles/permissions but in fact anything. Tracked here: https://github.com/pac4j/pac4j/issues/229

Maybe it's enough for your needs, but I agree and feel that something better (easier and more generic) can be built.

I'd like you to submit a PR in that direction and see where we are going to.

**Comment by leleuj** [comment]
Already addressed by #622
