### ISSUE TITLE
Supports cookies in the WebContext

### ISSUE THREAD

**Issue by leleuj** [pac4j/pac4j#279]
- create a new `Cookie` object

- create the `Cookie[] getRequestCookies()` and `void addResponseCookie(Cookie cookie)` methods to the `WebContext` interface

- create a `CookieClient`

**Comment by millross** [comment]
Could you provide an example of the use case for working directly with cookies from pac4j please? I want to make sure that I don't conflict with existing vert.x cookie handling :) or solutions to problems we might use cookies to solve

**Comment by leleuj** [comment]
I want the "best" design for pac4j v1.8 and implementations. So I have started trying to implement advanced use cases (I didn't commit anything).
My use case: I have a CAS server which generates a remember-me cookie which must be validated via a web service to grant the user a remember-me status.
To address that, I need to access the cookies of the request thus this issue.

**Comment by mmoayyed** [comment]
:+1: The WebContext interface already has methods that deal with responses. Adding cookie support is the next step.

**Comment by millross** [comment]
Ok, I think that works for me, though in the vert.x world it makes us dependent on use of a CookieHandler. Is use of your CAS server available to direct, or only indirect clients? The reason I ask is because setting up for an indirect flow in vert.x requires enabling of the CookieHandler anyway, but otherwise I'll need to document the requirement for the CookieHandler when using advanced use cases which need cookies (which in turn means that I'll need to know what those are :))

**Comment by mmoayyed** [comment]
I suppose cookie authN would be relevant to `DirectHttpClient`?

**Comment by leleuj** [comment]
The CAS server was just an example. It's the use case where the identity of the user is held by a cookie: it should be a direct client.

**Comment by leleuj** [comment]
Update in Play: https://github.com/pac4j/play-pac4j/pull/80
