### ISSUE TITLE
Log and throw

### ISSUE THREAD

**Issue by chameleooo** [pac4j/pac4j#320]
Hello,

I'm using pac4j and I'm wondering why you choose to you log exceptions before rethrowing them. I think it's not a good pattern because the exception already has the message and it can cause the message to be logged multiple times.

**Comment by leleuj** [comment]
I'm not sure unfortunately that we had a consistent strategy on logging exceptions.

Though, the idea was primarly to log for sure the exception when it's thrown, because some applications are sometimes badly configured and exceptions are "lost" somewhere in some root logging file. But indeed, some exceptions may appear twice in logs (which is not for me a big deal: better twice than zero).

Does it make sense?

**Comment by chameleooo** [comment]
I don't really understand how some exceptions can be "lost". But in both case, your logging can be lost and it's not a good pattern because you should only log if you handle the error.

In my application, errors logs are sent to the team by email. It's why this is a problem to me.

If you are ok with this rule, I can check pac4j code and propose you a pull request.

Here are some links I found googling this subject :
https://today.java.net/article/2006/04/04/exception-handling-antipatterns#logAndThrow
http://rolf-engelhard.de/2013/04/logging-anti-patterns-part-ii/
http://stackoverflow.com/questions/22072343/throw-exception-vs-logging

**Comment by leleuj** [comment]
Imagine you run your application on Tomcat and don't catch all exceptions: some are "lost" in the catalina.out while others are logged properly in the application.log file.

That said, I tend to agree with you: we cannot design an API because of the fact that applications badly log exceptions.

So please yes, don't hesitate to submit a pull request for that. Just marked this issue for version 1.8.1.

**Comment by leleuj** [comment]
PR: https://github.com/pac4j/pac4j/pull/322

**Comment by leleuj** [comment]
Thanks
