### ISSUE TITLE
Create a generic OAuth 2.0 client

### ISSUE THREAD

**Issue by leleuj** [pac4j/pac4j#409]
A bit like the `OidcClient`. At first, the `CasOAuthWrapperClient` could be based on this `GenericOAuth20Client` and maybe later on, other OAuth clients...

**Comment by ajherrick** [comment]
Sorry, I haven't had much chance to do anything with this other than think about it.

It seems like it may be difficult to make it generic and usable on its own while also having other clients be based off of it. It's like taking BaseOauth20Client and making it non-abstract.

If you have any ideas, I'll be glad to hear. Otherwise I hope to have a pr up to look at next week.

**Comment by leleuj** [comment]
No emergency, no hurry, I released pac4j 1.8.3, so it may be for pac4j 1.9.0 where I plan to try to refactor and clean stuffs here and there.
Hard to tell the best way, I think you need to struggle with the code.

**Comment by leleuj** [comment]
We already have generic OAuth clients with `BaseOAuthClient`, `BaseOAuth10Client`, ... and I don't think we can really do and need a better solution, based on our design (Scribe) and the OAuth protocol (more fuzzy than OpenID connect).
Closing for now. Feel free to re-open if you find a way.
