### ISSUE TITLE
Undergo a code audit

### ISSUE THREAD

**Issue by sambiomatters** [pac4j/pac4j#635]
Pac4J is rapidly becoming the best authentication framework for Java. It would be beneficial though to have some assurance that it is ready for production. An external code audit could achieve this. I propose a crowd funded security audit of the next stable version of PAC4J.

**Comment by leleuj** [comment]
pac4j is already used in production in many web sites, so it's already production ready.

That said, when it comes to adoption, many factors come into play: being well known, the quality of the documentation, how many people are involved, is there a commercial support... and indeed, for a security engine, a security audit could help in reassurance.

Lately, I've been focused in involving people and improving the documentation.

A security audit is a good idea. The question is the timing: would it make sense to perform it with 1.9.2 (the next stable version, end september) or for 2.0.0 (end 2016 / beginning 2017)?

Also, can you elaborate on the process to setup the security audit?

**Comment by mmoayyed** [comment]
I am not sure this is a good idea, if I understand it correctly, to mean: "the software has undergone security audit X and is now now secure & production-ready". 

No. The software comes with zero warranties. You as the adopter (or the adopters) are more than welcome to execute an audit independently and report back findings and submit patches.  If you deploy pac4j in production and somehow your hard-drive is wiped out because of a security issue, that's on you.

**Comment by mmoayyed** [comment]
Just to be clear: I am not against any sort of security audit. I am partially cautious of what it could mean and how it would be advertised.

**Comment by sambiomatters** [comment]
An audit is never a gurantee that it doesn't have vulnerabilities. That's well understood. What an audit would do was improve confidence that there are no obvious vulnerabilities. No one is asking for a warranty, just due diligence.

**Comment by mmoayyed** [comment]
I am sure that's what an audit does. I am not sure that's how an audit is understood :) It actually isnt well understood all that much. I have been involved with way too many "But I thought...wasn't that because...it was my understanding that...didnt you just say..." statements to care. I don't want to be involved in those discussions, regardless of how many times we loudly document what an audit means. (Who reads the docs, right?) So let's not even go there. Anyone is welcome to run any sort of audit and report back results in any shape or form and people have from time to time. I don't think pac4j directly should be involved directly at all. We'd be happy to take in contributions and make the platform better.

**Comment by mmoayyed** [comment]
Also I am not quite sure how a "crowd funded security audit" might work because I take that to be a very public thing by definition, and everything that follows in that context also happens to be quite public. "We ran X number of checks. Here are the results, etc". Whereas, reporting vulnerabilities and security issues in general should be a very private channel directly to the authors of the project and the trusted collection of developers.
