### ISSUE TITLE
Logout OK should be a 204

### ISSUE THREAD

**Issue by victornoel** [pac4j/pac4j#701]
Hi,

The implementation of ApplicationLogoutLogic returns a 200 when there is no redirect configured.

Since there is no content in the answer, the OK should be a 204 and not a 200.

**Comment by leleuj** [comment]
You are certainly right, but 204 is a bit exotic, isn't it? It's not a very well-known HTTP status code, but we can plan that for v2.0.

**Comment by millross** [comment]
I’m not sure it’s that exotic - we were certainly using it for “no content” on my last project. At the least I’d like it to be configurable from an enumeration of reasonable values (probably just 200/204) for login success.

**Comment by leleuj** [comment]
You're too good as a developer ;-)  I do many technical interviews and when it comes to HTTP status codes, believe me, I feel lucky when the applicant knows about 200, 404, 500 and 302.

That said, I have nothing against changing the default returned status code to 204 or being able to set that.

**Comment by millross** [comment]
I only found out about 204 a year ago, when working with the Eureka API :) And now I probably evangelise 204 for No Content a little too much :)

**Comment by victornoel** [comment]
It's a bit of  a detail, it's true ^^ but well, an OK without any content is 204, it's what is expected by clients :)
Actually, I wonder if the browser will happily show a blank page in case of 204...

**Comment by mmoayyed** [comment]
This is a breaking functionality. 

If an application decides to call: ` this.applicationLogoutController.applicationLogout(request, response);` prior to rendering some kind of logout page, that page basically goes kaput and errors out.

**Comment by millross** [comment]
Just to confirm, if you're going to return something containing a body it should have a 200 status code, if no body it should be 204. If you want to render a logout page, shouldn't you be redirecting to that page? Maybe I'm misunderstanding your comment.

**Comment by mmoayyed** [comment]
Sequence:

1. Navigate to /logout
2. Some controller takes over; does logout stuff
3. Pac4j session is cleared out perhaps via the logout controller as a followup 
4. Blank/Error page. (where a logout page here needs to be displayed)

Mostly 3 needs to be worked out in a different way.

**Comment by millross** [comment]
That doesn't feel like it's caused by this change which is about the change of status code to 204 where there's no content. Though I think you should reference your sequence in the new issue you've just raised along with how your proposal fixes the problem in 3.

**Comment by mmoayyed** [comment]
It's most certainly caused by this change. The logout controller clears the content and sets the status to 204 on the ok() call. This is a different issue altogether than #754 which is mostly about refactoring code. 

This is the "buggy" call:

```
if(redirectUrl != null) {
            action = HttpAction.redirect("redirect", context, redirectUrl);
        } else {
            action = HttpAction.ok("ok", context);
        }
```

It should somehow be allowed to say: don't do anything. Leave it be.

**Comment by mmoayyed** [comment]
PS I'd be happy to create a separate issue once @leleuj confirms this.

**Comment by millross** [comment]
But if it cleared the content and set the status to 200 you’d see the same problem. In other words, the change of status code from 200 to 204 (which is what this change is supposed to be) isn’t the issue.

**Comment by millross** [comment]
I don't see this code in either of the commits which were submitted under this issue. Sorry if I'm being obtuse, but the changes I see in both commits appear to be isolated to changing the status code. 

if(redirectUrl != null) {
            action = HttpAction.redirect("redirect", context, redirectUrl);
        } else {
            action = HttpAction.ok("ok", context);
        }

I don't dispute that the scenario you outline is a bug, I just don't see it in the changes submitted for this issue,.

**Comment by millross** [comment]
(The PR I'm looking at for this issue is https://github.com/pac4j/pac4j/pull/723/files, which doesn't appear to touch the code you reference. Am I misreading it or is there another PR associated with this issue which does change that code?)

**Comment by mmoayyed** [comment]
In my analysis, that's the only thing that breaks the app for me is the 204 status code. If I simply replace 204 with 200 and bypass that behavior, I don't get an error.

**Comment by millross** [comment]
But the change to 204 from 200 doesn't introduce that behaviour.

**Comment by millross** [comment]
For what it's worth, I think the Logout stuff should allow configuration of a function to convert a WebContext to an HttpAction as a mechanism for writing out whatever response you want in the event of no redirect being configured. Then you could offer default 204/no content but also offer any other chosen behaviour (and even offer standard functions for standard behaviours such as ok(String body), ok(Function<WebContext, String> bodyGenerator) etc).

**Comment by victornoel** [comment]
anyway, this issue is closed and what you have a problem with isn't related to the issue (maybe to the fix of the issue), just open another one with the description and ask for a redirection from logout in complement of answering 204. If it was working before, it wasn't expected to I think, it was a "useful side-effect" and we shouldn't rely on implicit side effects to solve problems ;)

**Comment by mmoayyed** [comment]
There is no such thing as a useful side effect.

**Comment by victornoel** [comment]
anyway, you got my point I think, no?

**Comment by mmoayyed** [comment]
I am not really inclined to "fix" anything because I decided to bypass it altogether and remove the "faulty" component in this case. So all is well on my end and there isn't anything for me to fix. I am just giving everyone [the wider public] a heads-up here in case they run into the same problem as this does appear to be a breaking [and somewhat invisible] change. Take that as you see fit. As I said all I see as the delta is 200->204. That's the feedback the user is providing here. If it works for you, great. If it does not for someone, they can take it up with pac4j later as my issue is goner with that removal.

**Comment by mmoayyed** [comment]
Also if it wasn't obvious, my intention certainly isn't to point fingers :) Not at all. Apologies if the post was misleading. This is simply a reportage of what appears to be a problem. That's all.

**Comment by victornoel** [comment]
Well, if everything is working on your end, at least that good.

I think the correct way to implement redirect on logout is by using the redirect functionality (already present in the logout logic), not by relying on a 200 return code (which doesn't mean `redirect`).
I don't see how a redirect could have happened before except if some other component was misinterpreting the 200 that was previously sent. Worst case it is a bug in this other component (what I called a "useful side effect").

For the record (for people interested in the discussion or hitting the same problem as @mmoayyed ), I believe the logout filter (i.e., `ApplicationLogoutLogic`) that is installed on an url such as `/logout` should be the sole "controller" behind this url, no other controller should handle it, so a correct flow would be:

1. send user to `/logout` by clicking on a logout button
2. `/logout` redirects you to the configured `redirectUrl`, e.g. `/logedout.html`
3. `/logedout.html` is shown

In case one needs to do more specific things on logout, then I guess (not sure about that, @leleuj?) either the logout filter (i.e., `ApplicationLogoutLogic`) shouldn't be used and logout() should be called on the `ProfileManager` or we could subclass the `ProfileManager` to introduce more complex behaviour for the `logout()` (which would be called by the filter).

P.S.: no offence taken, just trying to find a correct solution to a real problem :)

**Comment by millross** [comment]
I lean towards the idea that we should extend ApplicationLogoutLogic so that a generator for an HttpAction from a WebContext can be injected, rather than using 

if (redirectUrl != null) {
            action = HttpAction.redirect("redirect", context, redirectUrl);
        } else {
            action = HttpAction.ok("ok", context);
        }

Then the generator can actually be called prior to calling manager.logout etc to generate the action (which could be a redirect, it could be a 204 with no content, it could be a 200 with content, or anything else the implementor wanted - we could offer utility methods as factories for the different kinds of generator), and do any necessary context population, meaning that the generator has access to everything in the session as well as anything around the request. Then we clear down the session, and finally we return httpActionAdapter.adapt(generatedAction.getCode(), context). In other words, we, for example, build all the url matching stuff into the action generator, not keep it in the ApplicationLogoutLogic. Then we still have to decide what our default action generator should be (suggest a redirect to a default url provided in the constructor of the logic for now), but it becomes very easy to override without having to rewrite all the logic. 

I'm a bit uncomfortable explaining this with words, but i hope the idea makes sense.

**Comment by millross** [comment]
(See profileManagerFactory in DefaultApplicationLogic for the idea I'm trying to explain)

**Comment by victornoel** [comment]
@millross yep, it makes sense, I get the idea :)

But this means a change in the way filters are configured in a way: from a set of filter's parameter, we move to a set of filter's configurators.
It's great for programmatic configuration, but I don't know how it will work with stuffs like j2e-pac4j where configuration is done in a file… I know that for dropwizard-pac4j, it's not a problem.

Maybe this discussion should be moved in another issue @millross? :)

**Comment by leleuj** [comment]
I like to make things easily extensible. At the same time, we must provide consistent behavior and simple logics for people to understand how pac4j works.

Regarding the logout and its logic:

```java
if (redirectUrl != null) {
  action = HttpAction.redirect("redirect", context, redirectUrl);
} else {
  action = HttpAction.ok("ok", context);
}
```

Things are fairly easy.
Either you have a redirection URL (you give one or have a default one) and you'll be redirected to it after logout
OR
you don't and an empty page will be return (so the change from 200 to 204).

@millross : what do you want to customize on this?

**Comment by victornoel** [comment]
@leleuj I think the need for customization comes from @mmoayyed's use case where he seemed to need specific logout behaviour for its application, not only pac4j's behaviour.
I think extending the ProfileManager is also an option for that use case.

**Comment by millross** [comment]
My understanding was that Misagh wanted a 200 response with content (which couldn't be handled by extending the profile manager but could by injection of behaviour) without a redirect. If I'm wrong fine. 

Extension of profile manager can work but remember that to do so but still use the Default...Logic you need to inject a profileManagerFactory function for that to work (or use a custom extensor of the relevant Logic class).

**Comment by leleuj** [comment]
I told you that the too-esoteric 204 status code would make troubles ;-)

Returning from https://github.com/pac4j/pac4j/issues/754, as "premature optimization is the root of evil", I think the same apply for customizations: should we make every component in pac4j customizable? definitely no.

We must wisely choose which components must be extensible / customizable.

We have received many inquiries for changes on the behavior of the clients, that's why we work on https://github.com/pac4j/pac4j/issues/622
Many request on profile customizations as well, thus https://github.com/pac4j/pac4j/commit/79642ab995439c7a71495ae56e56ecfba8fc8eda

We have seen that the`ProfileManager` is sometimes customized for frameworks (Vert.x, Spring Security, Undertow...)
Good
For logics, I find it dangerous to make customizations easy: this is unlikely and risky to foresee the consequences / side-effects of such changes

**Comment by victornoel** [comment]
I agree :) (except for the esotericity of 204 :P)

Maybe @mmoayyed you could open an issue with only your use case that you can't easily implement with the current state of pac4j? Like this we could simply discuss it and see if there was a nice and easy way to answer it instead of making too general customizations.

**Comment by mmoayyed** [comment]
Sure. Can do.

**Comment by victornoel** [comment]
@leleuj I think we should reconsider fixing this issue for pac4j 3.
I understand that it may means doing some changes in other components of pac4j (see #755 were it was decided to revert the fix) but this is too bothersome to have some incoherent behaviour with regard to the HTTP spec…

I believe we should:
 - forbid calls to HttpAction.ok with an empty body
 - call HttpAction.noContent during logout

**Comment by leleuj** [comment]
Respecting the spec is sometimes harder than not respecting it. I'm willing to give it another try.

I'm in line with your proposal.

**Comment by victornoel** [comment]
Ok :)

I think it is especially important now that there is more and more HTTP clients that are not simply the brower (I'm thinking of SPA, my problem arose again today with angular's httpclient).

**Comment by leleuj** [comment]
Thinking a little more about this, I think: "forbid calls to HttpAction.ok with an empty body" is too much. Let's add the `noContent` method and switch the calls we can to it.

**Comment by leleuj** [comment]
And revert if issues arise...
