### ISSUE TITLE
Should FormClient use callbackUrlResolver to compute the loginUrl?

### ISSUE THREAD

**Issue by victornoel** [pac4j/pac4j#702]
Hi,

I was going through some code with respect to callback URLs and such, and noticed that the `FormClient` was computing the actual `loginUrl` (used when an authentication fails).
But I don't see the point of using the `callbackUrlResolver` in that case, actually the opposite, because this is not an URL that will be passed to an external system like the `callbackUrl` would.

I assume the role of the `callbackUrlResolver` is to give a way to pac4j to compute an URL that points to one of its endpoint but with the full host, port and everything, so that it can be passed to an external system. But maybe I'm mistaken?

I saw some similar behaviour in the `CasConfiguration`, but it's too complex for me to clearly understand what the URLs are used for… (and actually, the `loginUrl` goes through the `callbackUrlResolver` twice… in the `CasClient`/`DirectCasClient` and in `CasConfiguration`)

**Comment by leleuj** [comment]
You're right, but the `loginUrl` is like the `callbackUrl`, a URL of the application which could be defined in a relative way and expand with a specific `CallbackUrlResolver` according to the environment it is deployed to (for example).
The login URL of the CAS server is not part of the application, but the idea is to consider that for a global environment where you want to expand all URLs. It might go too far I admit, but we could imagine replacing some parts of the URL with placeholders, that's why it is applied to all URLs.

**Comment by leleuj** [comment]
Closing for now. Feel free to reopen if you think we need to change something.
