### ISSUE TITLE
Logout issue with response status code 204

### ISSUE THREAD

**Issue by mmoayyed** [pac4j/pac4j#755]
This is the behavior I am seeing with v2 SNAPSHOTs:

1. Request goes to `/logout`
2. Logout is handled by an application controller of some kind. Processes stuff
3. `ApplicationLogoutController` provided by pac4j webmvc that is also mapped to `/logout` kicks in and does its job.
4. Response status code is set to 204. Response cleared.
5. The application then takes over and attempts to render a logout [htm|jsp] page.
6. Server errors out, reporting a status code of 204.

This **exact sequence/behavior** works perfectly fine with the latest 1.9.x. 

So issues:

1. This is a very sneaky error. Took me a good couple of hours to track this down and understand why. Time is money? 
2. An HttpAction that seemingly does `ok` should not produce a 204?
3. Something should `WARN` in the logs? 
4. [Does the switch to 204 actually solve a problem](https://www.youtube.com/watch?v=xFVDNTXIC_Y)? 

My solution was to bypass what `ApplicationLogoutController` does and do it manually. This may be something `pac4j webmvc` ends up fixing, but as far as I can tell, this is very much a [regression that breaks "user space" in an *invisible* way](https://lkml.org/lkml/2012/12/23/75).

**Comment by victornoel** [comment]
I think the problem is that pac4j is not built to be used in conjunction with another controller for the response of logout (and callback).
pac4j expects that it will be the sole responsible of rendering and answer (in jax-rs-pac4j, I added an option so that, by configuration, the application developer can handle the response himself).

Until the 204, it worked as a side effect of the fact that the response wasn't committed by pac4j.

One solution at the application level (i.e. step 4) would be to set the response status back to 200 before rendering the logout page (and hoping that in the future pac4j doesn't decide to do something else to the response that would prevent it to work, since, I repeat, pac4j expects to be the sole responsible of the response). another could be to simply use logout redirect mechanism to do the redirect but that's not the best I guess.

There is no problem with 204 in itself until we decide that pac4j is not the sole responsible of the response.
I.e., it would mean to go back to @millross proposition where instead of letting pac4j decide how to respond, the developer would provide its own implementation of the response. In that case he could decide to answer 204 or to render a page or ot redirect or to let another controller take over as in your example.
A simpler version of it would be to specify the default response in case there is no redirect, so that one could either do nothing (and let the application take over just after) or one could use the default which is, for now a 204, or could change in the future (who knows).

So issues:

1. it's not a sneaky error, it is a misinterpretation of the behaviour of pac4j from the application developer, it's too bad,  and the HTTP specification was there pac4j even existed, sorry :)
2. if there is no content, it should be 204, the question is: should it be pac4j that is responsible of the response? for now it is the case...
3. WARN what? I think documentation would be preferable to better document what is expected of the user of pac4j on these cases (the same happens with callback and even the security filter on some cases, since it takes care of redirecting on behalf of the application).
4. you really don't like this issue, right? :P v2.0.0 is meant to break things, what if we stopped focusing on the past and tried to find elegant solution to real problems please?

Could you try the proposed solution at the application level and see if at least it solve your problem while continuing to use pac4j's abstractions? Then we could document this kind of use case and the proper solution to it (see point 3)
And in the long term, we can start thinking how this can also be solved at pac4j level (see point 2).
(point 1 and 4 are just us trolling, let's stop it, no?)

**Comment by mmoayyed** [comment]
I feel like I may need to repeat myself: I don't really have to try any of the proposed definitions/solutions because my solution was to remove usage of `ApplicationLogoutController ` that takes advantage of this 204-setting. That turned out to be a much simpler solution than writing abstractions and interfaces, etc for something that takes 2 lines. 

If there a need for someone to really use that controller in conjunction with the change applied here, hopefully they will bump into this thread and figure out what to do. 

>Then we could document this kind of use case and the proper solution to it... 

This simply could have been avoided with a WARN entry that says: "XYZ is happening. Change in behavior. Be aware.". Devs are way more inclined to read logs than to google search for docs. You are familiar with the history of RTFM, right? Ever wondered how that acronym came into existence? Ever wonerdered why RTFL (Logs) does not exist? :) 


> it is a misinterpretation of the behaviour of pac4j from the application developer

This statement is exactly why I dislike this issue. The change resulted in a change in behavior that is sneaky and invisible. Nothing breaks the application, except strange discoveries at runtime. That is definition of sneaky behavior. Even IF this was an actual bug, it really seems the change was made for the sake of making the change to make things ["compliant"](https://lkml.org/lkml/2012/12/23/75) with the specification. 

>  v2.0.0 is meant to break things,

This is also a strange statement, no offense. I am sure you can jump into a cacti field with arms wide open too. Just because you can do something, doesn't mean you should. Breaking changes should be avoided AT ALL COSTS where/when possible or they are just going to leave a poor taste. Change for the sake of change is bogus specially if the everyone relies on the "buggy" behavior and is perfectly fine with. That line of thinking will just make upgrades more difficult and will deter people from using the library. So stop that.

I don't mind breaking changes, IF they do serve a purpose and solve a real problem...and as long as the changes are LOUD and explicit such that they produce warnings/errors in the logs or break the application upfront and prevent it from building. This change did none of those. It simply resulted into wasted time tracking it down and fixing it to be more compliant with the spec supposedly where in practice, it provided zero pragmatic benefit. There is no evidence I have read that says the change fixes a problem, removes pain and provide benefits other than: hey it looks better this way 'cause this document says so. 

> point 1 and 4 are just us trolling

I am only trying to have a rational conversation about our approach to development...and I reserve any and all rights to loudly complain about breaking behavioral changes [and less about API changes] that waste dev time.

**Comment by victornoel** [comment]
> I feel like I may need to repeat myself: I don't really have to try any of the proposed definitions/solutions because my solution was to remove usage of ApplicationLogoutController that takes advantage of this 204-setting.

I was just asking for your help finding a clean solution that did not involve removing pac4j code...

**Comment by victornoel** [comment]
(and the change was motivated, it wasn't compliant with the HTTP specification)

**Comment by leleuj** [comment]
@mmoayyed let's be cool, tomorrow it's black Friday ;-)

I understand your concerns and frustration in wasting time for such a change. I'm in line: we should not change things just to change things.
But the idea here was fairly simple: it's better to return a 204 (instead of 200) when the logout returns no content (which is one of our use case), so we made this change in 2.0.0 (because it's still a runtime breaking change, the response status code changes) and even I don't think it was a priority, I was really confident it would not cause trouble.

The `ApplicationLogoutController` is meant to be used alone but we should be able to wrap it in another controller. I'm surprised by the problem caused by the 204 status code, it feels really strange that the server fails on that. I'd like to have some details on this.

I still think it was a good idea to change the 200 into a 204, but the reality has proven it may cause issues and as it's not a very important / really required change, I'm in favour of reverting it.

**Comment by millross** [comment]
No disagreement for reverting it as we weren't previously deluged with requests to make it 204 anyway. However, I think it's important that we should understand (maybe with a very small piece of sample code) why it changed. If we're wrapping in a way which should return content, then in that case a 204 is incorrect and our "Pac4j will either redirect or return an empty response" approach is not the right one. The bottom line is that it should be possible to switch off the "empty response" behaviour if that is not what is desired (which it seems to me is this scenario) rather than using a 200 for an empty response. In short, the desire to return content which is step 5 above is inconsistent with what the DefaultApplicationLogic does, as specified at http://www.pac4j.org/docs/how-to-implement-pac4j-for-a-new-framework.html#c-application-logout  which says:

1) after logout, the user is redirected to the url defined by the url request parameter if it matches the logoutUrlPattern

2) or the user is redirected to the defaultUrl if it is defined

3) otherwise, a blank page is displayed.

I think (3) should be "delegates to the application to determine what to display".

**Comment by victornoel** [comment]
Good idea!

Actually, the way the logics are written, they already give the wrapper the possibility to override what happens, this is the role of the `HttpActionAdapter` passed to the `perform` method! This is what I use in jax-rs-pac4j to give the user the possibility to let the jax-rs framework take care of the request.
But I needed to make the wrapper responsible of this, which isn't the case currently with most of the wrappers, and the `HttpActionAdapter` is not exploitable by users for now.

**Comment by victornoel** [comment]
By the way, this situation also exists for the callback logic IMHO. If we start changing the line where pac4j stops taking responsibility and leave the application take care of things, then it should be coherent for all the logics I guess…

**Comment by millross** [comment]
Callback is slightly different as you can define the 401/3 response body. And in any login process involving a callback you either get redirected to the page you requested (following profile population) or a forbidden/unauthorized response. However there is no “Http Action” status code corresponding to “Logged out”. I wouldn’t see a need to change callback. However, if a 200/with body response is an outcome then if Pac4j wants to own the response, it has to accommodate this outcome.

**Comment by millross** [comment]
Also uncomfortable with saying "let's intercept 204 responses in the HttpActionAdapter and do something else" - that's not intuitive for someone reading the code as it doesn't tell that person that this is how to exert control over logout behaviour. Plus what happens if we identify another scenario where 204 is correct that isn't logout-related? Then you're also rewriting that response too. Of course we could implement a special subclass of HttpAction called "LogoutFallbackHttpAction" (to be thrown where we currently spit out a 204) which could be specifically intercepted in that adapter if required. That would make the intent clear.

**Comment by victornoel** [comment]
> Callback is slightly different as you can define the 401/3 response body. And in any login process involving a callback you either get redirected to the page you requested (following profile population) or a forbidden/unauthorized response. 

Yep it's true, it's not the same!

> Also uncomfortable with saying "let's intercept 204 responses in the HttpActionAdapter and do something else" - that's not intuitive for someone reading the code as it doesn't tell that person that this is how to exert control over logout behaviour.

Agree, I was just stating what already existed :)

Personally I really don't like this `HttpAction` thing, I don't get why we use these half-values / half-exceptions that on top of giving information also modify the http response implicitly, it's really problematic!
It would be better to have the logics return in a way or another their response, and then the wrapper would decide what to do with them. Or the logic could simply modify the response and return nothing.
But doing both is kind of strange, even more because we are not always sure in which form this information arrives (exception or return value).

**Comment by leleuj** [comment]
For sure, I'd like to know more about the error Misagh encountered because it feels really strange.

As I said in another issue, we must careful in extending things. It's like premature optimization, you should not make components customizable if it doesn't make any sense.

I think the logics are the pillars of the pac4j model. I don't think they should be easily changed (subclassing is more than enough for me). Most other components are already extensible. Seeing questions and inquiries in the mailing list, my feeling is that we have open pac4j enough (the `ProfileDefinition` is for me one of the latest changes for that).

Apart from the 204 vs 200 debate, I haven't seen any inquiry about being able to override our logout mechanism. I've seen inquiries to handle central logout, but that's all and we'll work on that.
I tend to say that if you want to customize our logout, you just need to create your own controller, instantiate a `ProfileManager` and call the `logout` method and do your own logic.

I'm reluctant to the proposed change.

About the `HttpAction` thing, it may feel strange but it perfectly matches the way pac4j is designed.

Spring Security or Shiro have concepts: filters, tokens, providers... and authentication mechanisms are built on them.
To make pac4j easy, things are driven by two use cases: web services or UI login and the logics implement that. When it comes to customizing the behavior, there is one way: throw a `HttpAction` to break the flow. And yes, sometimes, a `HttpAction` may be also returned as indeed, it's an HTTP action to perform.

pac4j has been built almost only from my own reflection so other opinions are really necessary.

**Comment by leleuj** [comment]
I'd like to close a few issues before the RC1.

This was a long discussion.

@mmoayyed what was the issue with the 204 code?

PR to revert this change: https://github.com/pac4j/pac4j/pull/808
