### ISSUE TITLE
SAML2Client: Logout redirect action handles POST bindings incorrectly

### ISSUE THREAD

**Issue by mmoayyed** [pac4j/pac4j#790]
There exists the following block for the SAML2 client:

```java
protected RedirectAction retrieveLogoutRedirectAction(WebContext context, SAML2Profile currentProfile, String targetUrl) {
       ...
        if(this.configuration.getDestinationBindingType().equalsIgnoreCase("urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST")) {
            location = adapter.getOutgoingContent();
            return RedirectAction.success(location); //this is problematic
        } else {
            location = adapter.getRedirectUrl();
            return RedirectAction.redirect(location);
        }
    }
```

If the binding is HTTP-POST, the `RedirectAction` returned from that call above is buggy, because if I then do `httpAction.perform(...)`, pac4j basically ends up executing a `HttpAction.ok("redirection via 200", context, this.content);` which is wrong for this case. A post binding is supposed to actually do a POST. Not just write stuff out back out to the response.

Do we want to introduce a new `POST` type for `private RedirectAction.RedirectType type;`?

**Comment by mmoayyed** [comment]
Also the `else` clause needs to check and be activated only for a redirect binding. All other bindings must be thrown as errors for now, as unsupported types (and they are a bit less common than others anyway)

**Comment by leleuj** [comment]
My feeling is that we should have a `RedirectAction.post(location)` which would do a `RedirectAction.success(formPage)` where `formPage` is an HTML page with automatic form POSTing to `location`. Does that sound good?

**Comment by mmoayyed** [comment]
- Who designs the formPage? 
- Why not just accept a url and post data to it?

**Comment by mmoayyed** [comment]
Also `RedirectAction.post(location)` is rather misleading because it says "I have successfully handed off the post to a page to do the post" where it should more naturally say "I have successfully POSTed to a url".

**Comment by leleuj** [comment]
We design the formPage as a simple form with Javascript automatic form submission. Example:

```
<form action="post.php" name="FNAME" method="post">
<input type="text" name="example22" value="YOURVALUE" />
<input type="submit" />
</form>
<SCRIPT TYPE="text/JavaScript">document.forms["FNAME"].submit();</SCRIPT>
```

As it's done for SAML with the Velocity template. In fact, the signature of the method should be: `RedirectAction.post(String location, Map<String, Strin> data)`.

Yes, we could post to an URL directly with data. It depends on our needs. Don't we need to do that SAML action from the browser to send the cookies as well?

**Comment by taggiasco** [comment]
Hello,

I think Jérôme is right. The post (form submission) had to be done from the client side. Thus we send an OK 200 response and the client executes the JavaScript to perform a post to the IdP (post binding).
If we don't want this, we can send a redirect reponse and the browser will do the redirection (redirect binding).
Regards,
Matthieu

**Comment by leleuj** [comment]
Adding @jkacer which planned to work on SAML logout. BTW, any progress?

**Comment by jkacer** [comment]
Hi, I should start working on it this week.
Thanks for adding me here!

**Comment by leleuj** [comment]
@jkacer Any update on this? Did you confirm the bug?

**Comment by jkacer** [comment]
Sorry, not much free time so far, so I've only done some preparation work. I will confirm when I get to it. I firts thought this was just for my information. Sorry for the delay, gentlemen!

**Comment by jkacer** [comment]
It seems the code has been slightly refactored since this issue was created.
The referenced piece of code is now in `SAML2LogoutActionBuilder.getLogoutAction()`, which can be called from `IndirectClient.getLogoutAction()`, if `logoutActionBuilder` is an instance of `SAML2LogoutActionBuilder`.
Please correct me if I am wrong.

**Comment by leleuj** [comment]
Sure. But the core question remains: what does the `adapter.getOutgoingContent()` method returns? Is it only an URL or a full HTML page with form submission? I have tried to figure out by performing a SAML central logout myself, but it throws an exception (it might come from my SAML configuration, though).
So this still needs to be tested and checked.

**Comment by jkacer** [comment]
Yes, sure, I agree. That was just a note... I tried too with the J2E Demo project but the metadata used there has no Single Logout address. I'll have to get new/different metadata, maybe to a different IdP.

**Comment by jkacer** [comment]
A question has come to my mind: Can we call `getDestinationBindingType()` on the client's configuration in order to decide what binding to use? It's currently used for Login; may it happen that the bindings for Login and Logout are different on the IdP side? Shouldn't we have 2 configured bindings (login + logout) in that case? Maybe it's a rare case, I don't know...

**Comment by leleuj** [comment]
Currently, you have the J2E demo using TestShib and the Spring MVC demos with Okta, I guess this latter might be easier to configure for tests.

We can choose the binding via the `setDestinationBindingType` method on the `SAML2ClientConfiguration` class. But it's currently meant to apply globally. We could add a `setLogoutDestinationBindingType` method if necessary.

**Comment by leleuj** [comment]
@jkacer I just submitted a PR to support POST request on the `RedirectAction`: https://github.com/pac4j/pac4j/pull/840, it might be helpful here.

**Comment by jkacer** [comment]
Thank you, I'll check the Spring MVC demo if the SLO URL is there in the metadata. In the meantime, I was installing the newest Shibboleth locally, with the intention to run the single logout test against it. (I was not sure Test shib supported it, as the metadata does not contain the URL).

Concerning the new binding, it was just an idea/remark, if we can have it shared, I'm OK with it. It's not important at the moment...

**Comment by leleuj** [comment]
I doubt that TestShib supports logout and I don't see any logout URL in the Okta metadata (https://github.com/pac4j/spring-webmvc-pac4j-boot-demo/blob/master/src/main/resources/metadata-okta.xml). I think it will be much easier for you to use a local IdP.

**Comment by jkacer** [comment]
Finally installed Shibboleth 3.3 on local Windows :-) I could not get over it with the automatic Windows MSI installer so I had to install and configure it half-manually. But it's running now. The SLO URLs are in the metadata but commented out; I hope the URLs will work after uncommenting them...

**Comment by jkacer** [comment]
Already talking Shibboleth <--> PAC4J locally but it seems I'll need an LDAP server. First I thought I would set up IP-based authentication but it's not working for me, so I'm getting SAML responses with status Requester. I'll get one tomorrow and install locally.

**Comment by mmoayyed** [comment]
Why the LDAP server?

**Comment by mmoayyed** [comment]
ah you mean for authentication! Sorry. I typically use this:
https://github.com/mmoayyed/dummy-jaas-loginmodule

Or this:
https://github.com/jtgasper3/docker-images/tree/master/389-ds

Or this:
https://github.com/UniconLabs/unboundid-ldap-server

**Comment by jkacer** [comment]
Thank you very much, Misagh! I tried the dummy JAAS login module, reconfigured Shibboleth slightly and voila! It gives me an assertion, I am logged in :-)
It saved me a few hours of work installing OpenLDAP or a similar product...
The remaining 2 links look cool, although I did not test them.

**Comment by mmoayyed** [comment]
Not a problem! Glad you found it useful.

**Comment by jkacer** [comment]
Finally I was able to execute the full roundtrip and unfortunately I cannot confirm the original statement of this bug.
I have: j2e-pac4j-demo + j2e-pac4j updated an hour ago, running on localhost; Shibboleth 3.3 running on localhost too.
What I see happening after invoking the single Logout is (I have modified the port and added a context, please ignore these changes):

1. GET to http://localhost:8888/j2e-pac4j-demo/centralLogout?url=http://localhost:8888/j2e-pac4j-demo/?forcepostlogouturlafteridp - 200 OK - I get a form that POSTs itself to Shibboleth using JavaScript, a SAMLRequest is a field of the form.
2. POST to https://duck-notebook.prague.kacer.biz:8443/idp/profile/SAML2/POST/SLO - Shibboleth's Single Logout, seems to be working too. I get a very similar form that POSTs itself to j2-pac4j-demo, a SAMLResponse is a field of the form.
3. POST back to http://localhost:8888/j2e-pac4j-demo/callback?client_name=SAML2Client - returns 500 Internal Server Error with a very simple error page.

Stacktrace for (3):
`org.pac4j.saml.exceptions.SAMLException: Response instance is an unsupported type
	at org.pac4j.saml.sso.impl.SAML2DefaultResponseValidator.validate(SAML2DefaultResponseValidator.java:128)
	at org.pac4j.saml.sso.impl.SAML2WebSSOMessageReceiver.receiveMessage(SAML2WebSSOMessageReceiver.java:77)
	at org.pac4j.saml.sso.impl.SAML2WebSSOProfileHandler.receive(SAML2WebSSOProfileHandler.java:35)
	at org.pac4j.saml.client.SAML2Client.lambda$clientInit$0(SAML2Client.java:110)
	at org.pac4j.core.client.BaseClient.retrieveCredentials(BaseClient.java:61)
	at org.pac4j.core.client.IndirectClient.getCredentials(IndirectClient.java:123)
	at org.pac4j.core.engine.DefaultCallbackLogic.perform(DefaultCallbackLogic.java:79)
	at org.pac4j.j2e.filter.CallbackFilter.internalFilter(CallbackFilter.java:62)
	at org.pac4j.j2e.filter.AbstractConfigFilter.doFilter(AbstractConfigFilter.java:81)
`
So I think the POST redirect is done OK. What is failing is the handler that recieves the SAML Response back from the IdP because the validator is not able to validate this type of response (I haven't looked at it decoded yet).
FYI, I added the the following line to the SP metadata which is registered on the IdP side, not 100% sure if the URL is OK or if it needs to be something else:
`<md:SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="http://localhost:8888/j2e-pac4j-demo/callback?client_name=SAML2Client" />
`
If it's wrong then it might have caused the problem.

Does all this make sense to you?

**Comment by taggiasco** [comment]
Hi,
Indeed, the response validator has not been adapted for logout response. Neither the generation of the metadata part (I also added it manually).
As I already said, for me it seems right to get a 200 OK, and then let the JS make the post call.

**Comment by leleuj** [comment]
OK. Thanks for the feedback. Indeed, the logout callback URL of the app is the callback URL, but it should be able to handle SAML logout requests, which seems not to be the case yet. Keep us posted.

**Comment by leleuj** [comment]
I think we can close this issue and open a new one: https://github.com/pac4j/pac4j/issues/876

**Comment by jkacer** [comment]
Hello everyone and thank you for your answers. I was not sure about the logout URL, it's clear now. The JS auto-POST is also OK for me, there is other software that does the same (Shibboleth, for instance).

I'll move on to #876 ; I'll keep you updated...
