### ISSUE TITLE
Webcontext.getRequestContent() throwing IllegalStateException: STREAMED

### ISSUE THREAD

**Issue by Magic-WoW** [pac4j/pac4j#800]
I read one of your issues here where you added this method.

After calling it directly or by doing:
`J2EContext con = (J2EContext) context;`
first it throw the exception above and it's probably thrown because 
the code attempted to access `HttpServletResponse.getWriter()` after having already accessed `HttpServletResponse.getOutputStream()`

I'm trying to read the data from the body as JSON, not as URL parameters.

I'm using a simple IndirectClient:
`public class LoginFormClient extends IndirectClientV2<UsernamePasswordCredentials, CommonProfile>`

**Comment by victornoel** [comment]
It's not totally clear: are you the one calling `Webcontext.getRequestContent()`?

Where in your code and which framework are you using pac4j in conjunction with?
I don't think it is a bug, more of a question of whether it makes sense for you to call this method at the place where you are calling it... it is reserved for very specific cases where the request content must be read by pac4j (or an extension of some pac4j code) instead of by the framework you are using.

**Comment by leleuj** [comment]
Closing for now. Feel free to ask questions on the mailing list first.
