### ISSUE TITLE
setRedirectActionBuilder() is a one-time op?

### ISSUE THREAD

**Issue by mmoayyed** [pac4j/pac4j#803]
```
if(this.redirectActionBuilder == null) {
            this.redirectActionBuilder = redirectActionBuilder;
}
```

This is VERY counter-intuitive. Why is this done? (Yes a redirect action builder can only be set one on init perhaps. Why?) Either remove the setter and use ctor injections or remove the check. (Checks like this will also lead to ugly-only hacks to bypass such limitations.

**Comment by mmoayyed** [comment]
Not to mention that this is a "sneaky" op. If I keep calling that method with new builders over and over again, I get no warnings that what I am assuming to be set on that class is NOT in fact set, which would lead to needless troubleshooting.

**Comment by millross** [comment]
If it has to be a one-time only op, and we can't make it a final member set by constructor (which should be the preferred option for one-time-only sets), then we should throw an exception if this.redirectActionBuilder isn't null, rather than silently no-opping. As Misagh correctly points out, this is counterintuitive (and leads to a deceptive behaviour from the point of view of someone coding against it).

**Comment by leleuj** [comment]
More than a one-time operation, there is a default value consideration here. And I agree this is fairly ugly.

The idea is that for example, for the `SAML2Client`, in the `clientInit` method, I set `setRedirectActionBuilder(new SAML2RedirectActionBuilder(this));` as the default redirect action builder which you can override by explicitly setting your own by calling `setRedirectActionBuilder` on the newly created `saml2Client`. As you do that first, the default one is never set.

Here is my proposal: have a regular setter: `setRedirectActionBuilder` and a new protected `setDefaultRedirectActionBuilder` which checks if the component is null before setting the reference.

What do you think?

**Comment by mmoayyed** [comment]
I like your proposal. Thanks!

**Comment by leleuj** [comment]
Good. Will change things that way.

**Comment by victornoel** [comment]
@leleuj While we are at it, we should do the same for all the setters in that situation, for example in `DefaultSecurityLogic`, we have a `setProfileManagerFactory()` that could be facing the same kind of concerns (since it has a default value). And actually, most of the members of this class are in that situation.
I'm asking because I find myself needing to call `DefaultSecurityLogic.setProfileManagerFactory()` to set a default value if none was set on it (because it's coming from the `Config`, see #810 :)

**Comment by leleuj** [comment]
@victornoel Good point. Will take care of it as well.
