### ISSUE TITLE
ProfileManagerFactory settable in the Config

### ISSUE THREAD

**Issue by leleuj** [pac4j/pac4j#818]
and used by the logics with the following algorithm to select the appropriate `ProfileManagerFactory`:
1) if set in the `Config` object, use it
2) or use the one defined in the logics
3) which is by default a `ProfileManager`

**Comment by victornoel** [comment]
The `Filter`'s implementor (us) should be able to specify a default `ProfileManagerFactory` that will be used instead of the default one (point 3) too.
This is different than using a `ProfileManagerFactory` set by a user on a logic!

**Comment by leleuj** [comment]
I'm not in line with your previous comment here.

As we have one logic inside one filter, why is setting the `ProfileManagerFactory` on the filter not equivalent to set the `ProfileManagerFactory` on the logic?

I mean: why cannot we have this setter in the filter?

```java
public void setProfileManagerFactory(final Function<C, ProfileManager> factory) {
     logic.setProfileManagerFactory(factory);
}
```

As we exposed the logic via getter/setter, we certainly don't even need this `setProfileManagerFactory` setter at the filter level.

Am I missing something?

**Comment by victornoel** [comment]
A few remarks on this:
> As we have one logic inside one filter, why is setting the ProfileManagerFactory on the filter not equivalent to set the ProfileManagerFactory on the logic?

- it is equivalent, so it is superfluous since we can already do `filter.getLogic().setProfileManagerFactory()` without the need for introducing `setProfileManagerFactory` on the filter itself (as you actually said)
- it is problematic since `setProfileManagerFactory` is part of the `DefaultXXXLogic` but not part of `XXXLogic` itself I think, so actually it makes things incoherent or at least strange to manage

> Am I missing something?

My comment wasn't about that, it was about the same thing that motivated #823 : there is a difference between setting a default profile manager factory (that can be overridden via Config or via the aforementioned `setProfileManagerFactory`) and setting a profile manager factory (via the aforementioned `setProfileManagerFactory`).

For example in jax-rs-pac4j, I want by default that users use JaxRsProfileManager, so I want to set it somewhere, and I want users to be able to override it with their own.
That's all I want, whatever is the way to do it.

**Comment by leleuj** [comment]
So I think the solution is straightforward: when you instantiate the logic, you should set the appropriate `ProfileManagerFactory`, which can be then overridden by users. And we check the elements in the defined order.
Proposal: https://github.com/pac4j/pac4j/pull/826

**Comment by victornoel** [comment]
Seems good I think, since we are not in the same situation as with #823 (when the setter was called from `internalInit()`, so after a user may have set its own value).

**Comment by leleuj** [comment]
Indeed. Merging.
