### ISSUE TITLE
JWT generation does not like Profile from another JWT

### ISSUE THREAD

**Issue by ayethu** [pac4j/pac4j#828]
I'm doing a multi-stage login process where the first step is the normal email/password verification using DbAuthenticator. Afterward, I generate a JWT token based on the DbProfile for the client to use BUT it's a short-term token. The client then comes back with the first JWT token with additional data and at the point, I try to re-generate another JWT token based on the profile from the original token. The regeneration fails because the UserProfile has an attribute `profile.iat`. The check is in JwtGenerator but I also see that the other attributes that get checked are removed in JwtAuthenticator but `profile.iat` is left out. Any reason? 

I'm only on version 1.8.8 (due to limitations with ratpack) but I see the same logic in master.

org.pac4j.jwt.profile.JwtGenerator
````
        CommonHelper.assertNull("profile.sub", profile.getAttribute(JwtClaims.SUBJECT));
        CommonHelper.assertNull("profile.iat", profile.getAttribute(JwtClaims.ISSUED_AT));
        CommonHelper.assertNull(INTERNAL_ROLES, profile.getAttribute(INTERNAL_ROLES));
        CommonHelper.assertNull(INTERNAL_PERMISSIONS, profile.getAttribute(INTERNAL_PERMISSIONS));
````

org.pac4j.jwt.credentials.authenticator.JwtAuthenticator
````
        final Map<String, Object> attributes = new HashMap<>(claimSet.getClaims());
        attributes.remove(JwtClaims.SUBJECT);

		final List<String> roles = (List<String>) attributes.get(JwtGenerator.INTERNAL_ROLES);
        attributes.remove(JwtGenerator.INTERNAL_ROLES);
		final List<String> permissions = (List<String>) attributes.get(JwtGenerator.INTERNAL_PERMISSIONS);
        attributes.remove(JwtGenerator.INTERNAL_PERMISSIONS);
````

**Comment by leleuj** [comment]
OK. I see your point: we don't clean the `iat` attribute from the profile in the `JwtAuthenticator` which prevents you from generating a new JWT.

We don't work on 1.8.x anymore: I'll fix that on 2.0.x at least. As a workaround, the problem is that you can't remove attributes in 1.8.x from the profile, so the best would be to copy/paste the profile without the `iat` attribute.

The pac4j API has changed between versions: 1.8.x, 1.9.x and 2.0.x. Ratpack people want to keep the backwards compatibility in the 1.x stream, which is not possible when upgrading the pac4j version. So we're a bit stuck. It would be great if pac4j v2.0 could be integrated into Ratpack v2.0.

**Comment by ayethu** [comment]
Yes, that's what I ended up doing; manually copying the attributes from the original profile. 

I've been following the ratpack thread too on other issues and yes, I wish ratpack would try to move up the version since current pac4j 1.8.x version doesn't take care of JWT expiration also. Anyway, I don't think it's pac4js' responsibility. 

Thanks!

**Comment by leleuj** [comment]
After the release of pac4j v2 (May 2017) which will be a very mature version, I'll raise the debate again on Ratpack side.
