### ISSUE TITLE
Make pac4j fully multi-tenant

### ISSUE THREAD

**Issue by leleuj** [pac4j/pac4j#854]
The initialization process should not use the `WebContext` anymore (the callback URL must not be initialized once and for all, but for every web context). We need to remove the `InitializablewebObject`.
Only SAML and OAuth need to be updated in that way.

For SAML, things are a little more complicated regarding SP metadata generation as the callback URL is part of the metadata.

**Comment by millross** [comment]
I could do with understanding the SAML metadata generation stuff - since I'm the one who complained about the issues around reinitialising clients based on WebContext I'd like to see if I can help come up with a solution that doesn't have those problems (which might only occur under load) but which doesn't cause monstrous pain in general. Where can I find out more about the SAML metadata and its generation in a relatively easy-to-digest way? :)

**Comment by leleuj** [comment]
We should also remove the `reinit` method which does not play very well with async objects. If you want a new client configuration, use a new client.

**Comment by leleuj** [comment]
About the SAML metadata and its generation, I think we are a bit short on documentation, although we should have that here: http://www.pac4j.org/docs/clients/saml.html

A SAML application must generate a XML document with all its relevant information, this XML document must be registered in the SAML IdP to make it fully aware of the application and how to interact with it. The issue is that the computed callback URL (computed from the web context and thus having different values in a multi-tenant environment) is part of this XML document.

I don't think it's such a big deal anyway, we can generate **automatically** only one SP metadata by default and we can still ask **programmatically** for a specific metadata given a specific callback URL...

If you have troubles falling asleep, please read: https://docs.oasis-open.org/security/saml/v2.0/saml-metadata-2.0-os.pdf
