### ISSUE TITLE
SecretEncryptionConfiguration should accept byte[] secrets

### ISSUE THREAD

**Issue by ghenadiibatalski** [pac4j/pac4j#946]
Hello,

I'm facing a problem using the generated key with **SecretEncryptionConfiguration**. Current implementation uses a plain String. Thus this implementation is correct only for char[] but not generally for byte[] (like the keys generated by embedded key generator).

I would suppose, the class should accept the  byte[] keys just like com.nimbusds.jose.crypto.MACVerifier does.

It looks like the **SecretSignatureConfiguration** is also affected by this issue.

If you wish, i could propose the PR for this.

Regards, Gena

**Comment by leleuj** [comment]
Yes, we can do that, but don't forget to keep things backward compatible...

**Comment by gbatalski** [comment]
Not so easy even in this small code piece to preseve the backward compatibility. Do we need getter and setter for secret? Is the parameterless constructor necessary? I think, the instance should be immutable (no setter at all, some convinient constructors), otherwise the modification would be inconsistent: **setSecret(String)**, **setSecret(byte[])** but only **String getSecret()**. 

The only usage i've found within the CAS was the **TokenAuthenticationHandler** within cas-server-support-token-authentication. I could propose the modification for this module. The problem there is a little bit deeper. Is there the possibility to decode Base64 properties on the fly?

```json
"properties": {
        "@class": "java.util.HashMap",
        "jwtEncryptionSecret": {
            "@class": "org.apereo.cas.services.DefaultRegisteredServiceProperty",
            "values": [
                "java.util.HashSet",
                [
                    "BFSRBMSYpkQVXYPCOk4if6....." <= Base 64 Url encoded
                  //  "01234567891011121314151617181920"
                ]
            ]
        },
```
E.g. the property jwtEncryptionSecret is encoded and should be decoded before usage. Is there such a possibility to declare the decoder for a property or possibly other type as DefaultRegisterdServiceProperty? Sorry for "stupid" questions, i'm a newbie in cas/pac4j.

Gena
